version: '2'
services:
  nfldb-jpy:
    image: kakashi20/nfldb-jpy
    environment:
      - PGHOST=nfldb-pgsql
      - PGPORT=5432
      - PGUSER=nfldb
      - PGPASSWORD=go_cowboys
    ports:
      - "8888:8888"
    user: root
    volumes:
      - ./nfldb-jpy/notebooks:/home/jovyan/work
  nfldb-pgsql:
    image: kakashi20/nfldb-pgsql
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
  nfldb-phppgadmin:
    image: einfallstoll/phppgadmin
    environment:
      - POSTGRES_HOST=pnfldb-pgsql
      - POSTGRES_PORT=5432
      - POSTGRES_DEFAULTDB=nfldb
    ports:
      - "8080:80"
      - "8443:443"